apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: gitlab-pvc
   namespace: kasten-io
spec:
   storageClassName: managed-nfs-storage
   accessModes:
      - ReadWriteMany
   resources:
      requests:
         storage: 200Gi
