apiVersion: v1
kind: PersistentVolume
metadata:
   name: gitlab-pv
   namespace: kasten-io
spec:
   capacity:
      storage: 200Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Recycle
   storageClassName: managed-nfs-storage
   mountOptions:
      - hard
      - nfsvers=4.1
   nfs:
      path: /opt/backup
      server: 172.16.0.22
